In [2]:
import numpy as np 
import pandas as pd
from sklearn.neural_network import MLPClassifier

In [3]:
import pandas as pd
cell_df = pd.read_csv("helloFlood1sFrame.csv",sep=";")
cell_df.head()

second               src  DioCount  DisCount  DaoCount  OtherMsg  label
0    60.0  fe80::c30c:0:0:c         0       224         0         0      1
1    60.0  fe80::c30c:0:0:3        30         0         0         0      0
2    60.0  fe80::c30c:0:0:a         0         0         6         0      0
3    61.0  fe80::c30c:0:0:8         0         0        33         0      0
4    61.0  fe80::c30c:0:0:c         0       142         0         0      1

In [4]:
import numpy as np
feature_df = cell_df[['DioCount','DisCount','DaoCount','OtherMsg']]
X = np.asarray(feature_df)
X[0:5]

array([[  0, 224,   0,   0],
       [ 30,   0,   0,   0],
       [  0,   0,   6,   0],
       [  0,   0,  33,   0],
       [  0, 142,   0,   0]], dtype=int64)

In [5]:
#cell_df['Class'] = cell_df['Class'].astype('int')
y = np.asarray(cell_df['label'])
y [0:5]

array([1, 0, 0, 0, 1], dtype=int64)

In [6]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4,stratify=y)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (1536, 4) (1536,)
Test set: (384, 4) (384,)


In [7]:
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')


i=0
max = 0

clf = MLPClassifier(hidden_layer_sizes=(3,2),activation='relu')
clf.fit(X_train,y_train)

y_hat = clf.predict(X_test)




cm = metrics.confusion_matrix(y_test, y_hat)
print("Matriz de confusión:")
print(cm)

precision = metrics.precision_score(y_test, y_hat, average=None)
print("Precisión por clase:", precision)

recall = metrics.recall_score(y_test, y_hat, average=None)
print("Recall por clase:", recall)

accuracy = metrics.accuracy_score(y_test, y_hat)
print("MLP' Accuracy: ", accuracy)
print("MLP' f1: ", f1_score(y_test, y_hat, average=None))


Matriz de confusión:
[[302   0]
 [  2  80]]
Precisión por clase: [0.99342105 1.        ]
Recall por clase: [1.         0.97560976]
MLP' Accuracy:  0.9947916666666666
MLP' f1:  [0.99669967 0.98765432]


In [8]:
import emlearn
cmodel_c = emlearn.convert(clf, kind = "MLPClassifier")
cmodel_c.save(file="model.h")

'#include <eml_net.h>\nstatic const float model_layer0_weights[12] = { 0.000000f, 0.532974f, 0.566811f, -0.000000f, -0.096194f, -0.289263f, -0.046217f, 0.214632f, 0.650580f, 0.000012f, -0.019030f, 0.037212f };\nstatic const float model_layer0_biases[3] = { -0.152620f, 0.463197f, 0.696493f };\nstatic const float model_layer1_weights[6] = { -0.000000f, 0.000012f, -0.409626f, -0.000000f, -1.253383f, -0.011816f };\nstatic const float model_layer1_biases[2] = { 1.966223f, -0.337646f };\nstatic const float model_layer2_weights[2] = { 1.842166f, 0.183000f };\nstatic const float model_layer2_biases[1] = { -1.238827f };\nstatic float model_buf1[4];\nstatic float model_buf2[4];\nstatic const EmlNetLayer model_layers[3] = { \n{ 3, 4, model_layer0_weights, model_layer0_biases, EmlNetActivationRelu }, \n{ 2, 3, model_layer1_weights, model_layer1_biases, EmlNetActivationRelu }, \n{ 1, 2, model_layer2_weights, model_layer2_biases, EmlNetActivationLogistic } };\nstatic EmlNet model = { 3, model_layers