In [1]:
import numpy as np 
import pandas as pd
from sklearn.neural_network import MLPClassifier

In [2]:
import pandas as pd
cell_df = pd.read_csv("helloFlood10sFrame.csv",sep=";")
cell_df.head()

second               src  DioCount  DisCount  DaoCount  OtherMsg  label
0    60.0  fe80::c30c:0:0:8        60         0        71         0      0
1    60.0  fe80::c30c:0:0:4        30         0        51         0      0
2    60.0  fe80::c30c:0:0:c         0      1160        23         0      1
3    60.0  fe80::c30c:0:0:a         0         0         9         0      0
4    60.0  fe80::c30c:0:0:5        60         0         2         0      0

In [3]:
import numpy as np
feature_df = cell_df[['DioCount','DisCount','DaoCount','OtherMsg']]
X = np.asarray(feature_df)
X[0:5]

array([[  60,    0,   71,    0],
       [  30,    0,   51,    0],
       [   0, 1160,   23,    0],
       [   0,    0,    9,    0],
       [  60,    0,    2,    0]], dtype=int64)

In [4]:
#cell_df['Class'] = cell_df['Class'].astype('int')
y = np.asarray(cell_df['label'])
y [0:5]

array([0, 0, 1, 0, 0], dtype=int64)

In [5]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4,stratify=y)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (457, 4) (457,)
Test set: (115, 4) (115,)


In [13]:
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')


#no te tendrias que quedar con la que te de mejor accuracy?
i=0
max = 0
best_clf =0

clf = MLPClassifier(hidden_layer_sizes=(3,2),activation='relu')
clf.fit(X_train,y_train)

y_hat = clf.predict(X_test)


cm = metrics.confusion_matrix(y_test, y_hat)
print("Matriz de confusión:")
print(cm)

precision = metrics.precision_score(y_test, y_hat, average=None)
print("Precisión por clase:", precision)

recall = metrics.recall_score(y_test, y_hat, average=None)
print("Recall por clase:", recall)

accuracy = metrics.accuracy_score(y_test, y_hat)
print("MLP' Accuracy: ", accuracy)
print("MLP' f1: ", f1_score(y_test, y_hat, average=None))

Matriz de confusión:
[[104   0]
 [  0  11]]
Precisión por clase: [1. 1.]
Recall por clase: [1. 1.]
MLP' Accuracy:  1.0
MLP' f1:  [1. 1.]


In [7]:
import emlearn
cmodel_c = emlearn.convert(clf, kind = "MLPClassifier")
cmodel_c.save(file="model.h")

'#include <eml_net.h>\nstatic const float model_layer0_weights[8] = { -0.000000f, -0.409937f, 0.414686f, 0.321368f, -0.800480f, 0.262991f, -0.194687f, 0.000006f };\nstatic const float model_layer0_biases[2] = { 0.368131f, 0.815568f };\nstatic const float model_layer1_weights[4] = { 1.266918f, 0.612413f, 0.282060f, -0.788367f };\nstatic const float model_layer1_biases[2] = { -1.360967f, -0.062617f };\nstatic const float model_layer2_weights[2] = { 0.645962f, -1.161038f };\nstatic const float model_layer2_biases[1] = { 0.776101f };\nstatic const float model_layer3_weights[1] = { 0.192853f };\nstatic const float model_layer3_biases[1] = { 0.799992f };\nstatic const float model_layer4_weights[1] = { 0.336948f };\nstatic const float model_layer4_biases[1] = { -1.403981f };\nstatic const float model_layer5_weights[1] = { 0.400508f };\nstatic const float model_layer5_biases[1] = { -2.012227f };\nstatic float model_buf1[4];\nstatic float model_buf2[4];\nstatic const EmlNetLayer model_layers[6]