In [1]:
import numpy as np 
import pandas as pd
from sklearn.neural_network import MLPClassifier

In [2]:
import pandas as pd
cell_df = pd.read_csv("helloFlood5sFrame.csv",sep=";")
cell_df.head()

second               src  DioCount  DisCount  DaoCount  OtherMsg  label
0    60.0  fe80::c30c:0:0:b        30         0        31         0      0
1    60.0  fe80::c30c:0:0:4        30         0        37         0      0
2    60.0  fe80::c30c:0:0:9        30         0        68         0      0
3    60.0  fe80::c30c:0:0:8        30         0        33         0      0
4    60.0  fe80::c30c:0:0:5        30         0         0         0      0

In [3]:
import numpy as np
feature_df = cell_df[['DioCount','DisCount','DaoCount','OtherMsg']]
X = np.asarray(feature_df)
X[0:5]

array([[30,  0, 31,  0],
       [30,  0, 37,  0],
       [30,  0, 68,  0],
       [30,  0, 33,  0],
       [30,  0,  0,  0]], dtype=int64)

In [4]:
#cell_df['Class'] = cell_df['Class'].astype('int')
y = np.asarray(cell_df['label'])
y [0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [5]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4,stratify=y)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (837, 4) (837,)
Test set: (210, 4) (210,)


In [8]:
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')


i=0
max = 0
best_clf =0

clf = MLPClassifier(hidden_layer_sizes=(3,2),activation='relu')
clf.fit(X_train,y_train)

y_hat = clf.predict(X_test)

cm = metrics.confusion_matrix(y_test, y_hat)
print("Matriz de confusión:")
print(cm)

precision = metrics.precision_score(y_test, y_hat, average=None)
print("Precisión por clase:", precision)

recall = metrics.recall_score(y_test, y_hat, average=None)
print("Recall por clase:", recall)

   
accuracy = metrics.accuracy_score(y_test, y_hat)
print("MLP' Accuracy: ", accuracy)
print("MLP' f1: ", f1_score(y_test, y_hat, average=None))


Matriz de confusión:
[[189   0]
 [  0  21]]
Precisión por clase: [1. 1.]
Recall por clase: [1. 1.]
MLP' Accuracy:  1.0
MLP' f1:  [1. 1.]


In [7]:
import emlearn
cmodel_c = emlearn.convert(clf, kind = "MLPClassifier")
cmodel_c.save(file="model.h")

'#include <eml_net.h>\nstatic const float model_layer0_weights[8] = { -0.006261f, 0.214857f, -0.062762f, 0.000000f, 0.000000f, -0.004508f, 0.385347f, -0.024878f };\nstatic const float model_layer0_biases[2] = { -0.674363f, 0.344561f };\nstatic const float model_layer1_weights[4] = { -0.581874f, 0.399000f, 0.410562f, -0.000000f };\nstatic const float model_layer1_biases[2] = { -0.668313f, 1.075838f };\nstatic const float model_layer2_weights[2] = { -0.659056f, -0.648602f };\nstatic const float model_layer2_biases[1] = { -0.027613f };\nstatic const float model_layer3_weights[1] = { -0.000000f };\nstatic const float model_layer3_biases[1] = { 0.040088f };\nstatic const float model_layer4_weights[1] = { -0.054804f };\nstatic const float model_layer4_biases[1] = { -0.864816f };\nstatic const float model_layer5_weights[1] = { -0.265320f };\nstatic const float model_layer5_biases[1] = { -0.148093f };\nstatic float model_buf1[4];\nstatic float model_buf2[4];\nstatic const EmlNetLayer model_lay